---

- hosts: routers

  
  tasks:
    - name: Interface_configuation
      ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: Created for Ansible test!
          - name: loopback1020
            description: Created for Ansible loopback test
        state: overridden


